name: test action

on:
  pull_request:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout tauri-docs
        uses: actions/checkout@v2
        with:
          repository: tauri-apps/tauri-docs
          path: tauri-docs
      - name: checkout tauri
        uses: actions/checkout@v2
        with:
          repository: tauri-apps/tauri
          path: tauri
      - name: install webkit2gtk
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: generate rust docs
        working-directory: tauri
        run: cargo doc --no-deps
      - name: run rustdocusaurus
        uses: ./github-action
        with:
          originPath: ./tauri/target/doc/
          targetPath: ./tauri-docs/docs/api/rust/
          sidebarPath: ./tauri-docs/sidebars.json
          linksRoot: /docs/api/rust/
          cratesToProcess: "tauri,tauri_api,tauri_utils"
